#+AUTHOR: Caleb Beers
#+OPTIONS: ^:{}

* January
** Monday 1/30
*** Add missing billing categories #187
(note: merge this one before #189)

1. Put the links in `root.html.heex` under the right category (Accounting).
2. Make the selected categories in the multi-select be put onto the credit card when it's submitted. This involves reworking the controller and the template.
3. Make sure that the categories pre-selected in the multi-select are only those categories already on the card. Rework the assigns: `@assigned\billing_categories` changes to `@billing_categories` and `@assigned categories` stays the same.
4. Change schema names for credit card and paypal account to singular
5. Remove category\edit link and files
6. Resize and center edit and create modals for billing categories
7. Finishing:
   1. Run tests
   2. Manually test
   3. `mix compile --force` and fix all errors and warnings
   4. Remove inspects and puts
*** Feat/na i116 email identity management #189
1. Move the `New Identity` link up to the top under `Listing Identities`.
2. Likewise with `New Email`.
3. Import Ecto Commons validator functions to `schema.ex` so they'll be available to all schemas.
4. Add belongs\to(:identity) to the email schema and has_many(:emails) to identity schema.
5. Add select field to the modal for emails.
** Tuesday 1/31
*** Feat/na i116 email identity management #189
1. Address PR comments re: formatting and naming fields.
2. Need to find a way to generate a keyword list so first and last names are displayed but keyed to ids. This will take some research. It turns out that `select` as used in Phoenix templates will happily take a keyword list as an argument. The keys of the keyword list will be displayed as options, but the actual params that the form sends to the event handler will be the values of those keys. So I wrote a little function `generate\keyword_list/1` in `live_helpers.ex`, which sorts out the first and last names on a phone account and keys them to ids, then spits out a keyword list for neat display in the template. :-)
3. Allow identities to be added to emails. We need to abstract maybe\put_identity to a helpers file (probably in `schema.ex`) and make sure it's available from there. Also abstract out an assign_all_identities function (most likely to `live_helpers.ex`) and make that available to both the form components i email_live and phone_accounts.
* February
** Wednesday 2/1
*** Feat/na i116 email identity management #189
1. Need to fix error where NetAdminWeb cannot be found when user\settings_controller attempts to use it. Turns out that `mix compile --force` will fix errors like that.
2. Editing an email account to add an identity does not seem to work. Got it working, but had to change `identity\id` directly instead of changing the association. Let's see how we did it in `phone_account`... It was the `on_replace` option that did it. Let's fix that by changing to `:nilify` instead of `:update  `.
3. Change email to email\address in the email accounts migration, the email accounts schema, the email accounts context, the email accounts live views and components and templates, and the tests for all those.
4. Manually test
5. Run tests, make tests pass
6. Run `mix compile --force`
** Thursday 2/2
So far, the postgrex error is only coming up on Identities, Emails, and Phone Accounts, PayPal Accounts, and Credit Cards pages, not the Users page.

Anyhow, I checked the Postgrex error:

[error] Postgrex.Protocol (#PID<0.604.0>) disconnected: ** (DBConnection.ConnectionError) owner #PID<0.2692.0> timed out because it owned the connection for longer than 120000ms (set via the :ownership\timeout option)

Notice the PID is 0.2692.0. This matches the root PID for the LiveView socket at the time this was running, which implies that this is a LiveView issue. It happens no matter which root liveview we're using, but ONLY if we're using a liveview.

Made some minor fixes in the two open PRs. One was merged.
** Friday 2/3
*** (feat) [NA-I143] Seperate "notes" as a separate button and patch objects
We need a separate notes tag for:

1. Email Accounts
2. Identities
3. Billing Categories
4. Credit Cards *
5. Paypal Accounts

\* already has a notes field but needs the "notes" link removed from the grid and turned into a button. The button should change an assign that reveals the notes field.

Create some migrations to add a "notes" text field to email account, identities, billing categories, and paypal accounts.

For objects 1, 2, 3, and 5, the process is:

1. Modify the schema
   1. Add notes as a field under the schema definition.
   2. Add notes in all the appropriate changeset attrs lists
2. Create the text box component and make it reusable.
   1. This should be a modal that takes the assigns and can add
3. Modify the templates
   1. Add notes in the form components for each template
** Monday 2/6
It's too complex to add a modal-within-a-modal, so I'm going to refactor the form components to exist on parent edit liveviews. So for example, `form\component.ex` for phone identities will need to show up on PhoneIdentitiesLive.Edit. This will require a medium-size refactor. This will be a heavier lift than I thought.

1. Create an edit liveview for the other entities: billing categories, emails, identities, phone accounts.
2. For each of these, edit the router so that the `"entity/edit"` and `"entity/new"` routes point to the new edit liveview.
3. Add links in the appropriate place in the index liveviews.
4. Delete old modals and form components. Remove `apply\action` pipelines from parent controllers with names like `Entity.Index`.
5. Remove the hidden inputs and put a note button there to open the notes modal.

NOTE: I would like to set up the structural refactor to create "assign\changeset" and other "assign" functions for these liveviews. I'll get to that when I get back to the structural refactor.
** Tuesday 2/7
Right now we have four liveview entities:

1. Billing Categories
2. Credit Cards
3. Emails
4. Identities
5. Paypals
6. Phone Accounts

Step 3 of the list from yesterday for each one.
** Wednesday 2/8
Almost everything is set up. Now to put the finishing touches on the modal and add a note button.

The note button can start off as a simple button tag that emits a click event. That'll change the `notes?` assign and then make the multi-line note edit modal appear.

Looks like a button tag submits the form even when it doesn't have a `type="submit"` attribute. Solution: just make it some text and specify an event name in the div element.

Need to correct the tests to reflect the new structure in this refactor. Then add tests for the notes option.

And done! All tests pass, no warnings on `mix compile --force`

Tomorrow: run `git rebase netadmin\v2` and go from there.

** Thursday 2/9
Index controllers in these files:

1. Billing Categories
2. Credit Cards
3. Emails
4. Identities
5. Paypals
6. Phone Accounts

To add note button to grids:
1. Assign notes?=false in each index controller's `mount/3`:
   \ |> assign(notes?: [])
2. Add notes? event handler to each index controller:
  @impl true
  def handle\event("notes-field", %{"id" => id} = params, socket) do
    case socket.assigns.notes == id do
      true -> {:noreply, assign(socket, notes: [])}
      \ -> {:noreply, assign(socket, notes: id)}
    end
  end
3. Copy and paste this into each index heex:
          <td>
            <div phx-click="notes-field" class="notes" phx-value-id={entity.id}>Notes</div>
              <%= if entity.id == @notes do %>
                <%= entity.notes %>
              <% end %>
            </td>

Afterwards change paypal edit to show/hide notes as the other pages.
** Friday 2/10
---
** Monday 2/13
Return to working on structural refactor. Pluralize schemas and do some housecleaning.

Go over Tailwind PR and notes PR with Kyle.

Leave roles alone but change tooltip for billing categories to Tailwind.

Daisy UI is easy to add, so go ahead and add it.

** Tuesday 2/14

As it turns out, Tailwind has a set of default styles called "preflight" that overrides the default Phoenix styles. Disabled.

Also worked a little more on the structural refactor. I want to get this code nice and clean before more major changes are made.

** <<wed21522>>Wednesday 2/15
*** NA-I136
So, I need to set up a file upload so people can upload documents for an identity. Phoenix has a `fileupload` function built-in so that's what I'll use. Postgres can store binaries, so that's how we'll be storing our files.

The database design should be fairly simple: documents ought to have a "data" field for the binary blob. I will need to research how these are stored in postgres - might not need a field. It will need an `identityid` as a foreign key, and of course, each document will have its own `document_id`. By itself, those three should be sufficient, although it might also behoove us to have a `name` or `title` field just to have some way of referencing these things without seeing a UUID with a zillion random characters. So, the agenda here is:

1. Create a migration for the documents table.
2. Add a document upload field to the appropriate entities
3. Adjust the changesets and schemas. This will naturally be a `hasmany` relation between the entities and their files.

*** chore/structural refactor
For the structural refactor, we need:
1. Get rid of `no route found` error for favicon
2. Get rid of `no route found` error for static path

*** NA-I143
And on the `notes` PR, we need to move the notes button from the form to the grid. This applies to these entities:

1. Billing Categories
2. Credit Cards
3. Emails
4. Identities
5. Paypals
6. Phone Accounts

This will be accomplished by means of a notes modal that opens, takes a changeset for the given item, and only updates the notes field.

It seems that the notes modal needs a way to see what kind of struct is being passed in. There is a way to pattern match on structs, and it can certainly be passed in as an assign.

The other thing we need to do to make this work is make sure that every function for updating an entity in a context is named `update` not `updatethis_thing`. <-- undo this later (Thursday note)

To complete the update function in the notes modal, I will need to make it possible to select the right module for a given struct.

** Thursday 2/16
*** NA-I143
Continuing the notes modal work from yesterday. It's problematic to have a single modal that does all this because it must recognize the type of struct it's getting and call the correct context function. I'll just duplicate modals instead.

Note to self: when complexity seems overwhelming, premature optimization may have happened. Perhaps solve the problem with duplication instead.

** Friday 2/17
*** NA-I143
1. Copy notes modal to each live directory for each entity
2. Add routes for each modal
3. Copy and paste modal and notes link into each `heex`
4. Make modifications in each `heex`
5. Make modifications in each `notesmodal` controller.
6. Add `handle_params/3` call to get the entity id to each `index` controller.
7. Manual test
8. Remove the notes field from the edit views
9. Rebase or merge
10. Mix format
11. Make sure tests pass
12. Get rid of any warnings with `mix compile --force`
13. Push and request review

Note: it looks like the paypal and phone accout index pages have the edit and delete buttons grouped under a single `<tr>` with two `<span>`s. Should homogenize those in the structural refactor.

Ran into a very mysterious error where forms were not emitting events. As it turns out, forms cannot emit events from inside of tables, so the modal has to be set outside of the table to emit anything.

** Monday 2/20
*** NA-I143
Finished! PR is pushed for review. Added a quick last-minute change to `README.md` to clarify how Google OAuth works for this app.

*** NA-I136-implement-identity-documents
Resuming work from [[wed21522]].

A document should `belong_to` a entity, where that entity can `have_many` documents. Problem: a document can `belong_to` more than one type of entity. So we can't put `belongs_to: NetAdmin.Identities.Identity`, for example, because that locks documents to only one kind of entity. A polymorphic association would appear to be the solution. According to [[https://hexdocs.pm/ecto/Ecto.Schema.html#belongs_to/3-polymorphic-associations][the hex docs]], this is best accomplished in our case by simply adding a separate id field for each possible parent in the documents table.

We can add the extra fields by adding new migrations later. In the meantime, I'll just do identities. It is important that the `identities_id` be nullable. In order to take the approach described in the hex docs, any given `id` column must be nullable.

Chris McCord said in 2020 that components do not currently support file uploads, so I will need to refactor the `form_component.ex` into an `edit.ex` which will be its own parent LiveView.
** Tuesday 2/21
*** NA-I136-implement-identity-documents
First, make a list of files associated with an identity that shows up in the edit dialogue. Second, let's make them downloadable.

Direct downloads are not yet supported by LiveView so we'll write a Phoenix controller to do it for us.

Unfortunately, we can't just redirect to that controller and go back to LiveView. There is, as of yet, no good way to redirect from LiveView to a Phoenix controller and then get back to LiveView easily.

Instead, we'll do some magic with JS to serve the file via an event listener in `app.js`. We can push stuff to this listener using `push_event/3`, with an event name of "download" and a payload consisting of a map: `%{"uri" => Routes.download_path(socket, :document, id)}`. This map causes the phoenix controller designated by that route (this is `NetAdminWeb.DownloadController`) to open in a hidden frame. That controller serves the file. The `:document` argument to our route helper tells the controller to call `document/3`. In the future, if we wanna download anything else, we can add functions besides `document/3`.
** Wednesday 2/22
*** NA-I119-vps-management
Create resources for vps management liveviews.
** Thursday 2/23
*** NA-I119-vps-management
Fix CSS issue wtih checkboxes.

Need to:
1. Make currency a string for now
2. A country can just have a name and an id. Create schema/migration with `phx.gen.schema`.
3. Put the United States as a country in `seeds.exs`
4. Give the VPS schema a belongs_to relation to countries.
5. Make the country and currency selector on the form a dropdown based on work already done.
** Friday 2/24
*** NA-I119-vps-management
Need to address some PR comments.

1. Add migration and schema for currency table. Should have exchange rate and name.
2. Rewrite the countries migration to add specified fields: `abbr`,`country_code`. `name`, `iana_domain`, `itu_calling`, `currency_id`. The `currency_id` should be a foreign key to the currency table.
3. Add all the countries that Kyle sent me to `seeds.exs`.
4. Allow search to filter country names.
5. Change the migration and `vps.ex` so that only Name, Cost, and URL are required.
6. Add URL validation with Ecto Commons.
*** NOTICKET
1. Add Daisy UI to get components
2. use Daisy UI's provided dropdown component to add the "Research" tab.
** Monday 2/28
*** NA-I119-vps-management
Complete ticket.
** Tuesday 2/29
*** NOTICKET-add-daisyui-and-popout-menu
As it turns out, flexbox can become quite confused if it has heterogenous elements. So if you have `justify-center` for your flexbox items, it might not know that, say, an `<a>` element and a `<nav>` element are to be treated the same. So wrapping each individual element in a `<div>` can be quite helpful because flexbox will treat `divs` as homogeneous elements.

I think I should replace the current drawer with a sidebar from daisyui. The general pattern from here on out should be: each time I work on a component, I remove any legacy code and replace it with Tailwind/daisy. That way we can change the CSS over to tailwind without bothering with a single huge overhaul.
** Wednesday 3/01
*** NOTICKET-add-daisyui-and-popou-menu
Finish first draft. Next we'll want to merge the `form_component.ex` to the parent component.

*** NA-I145-implement-provider-research-registrar
Implement required functionality. This has a `form_component.ex`, however, so it will need to be merged to the parent liveview since that's the preferred behavior for this. Also, get rid of main scrolling behavior.
** Thursday 3/02
*** NA-I119-vps-management
Implementing the requested search behavior will take a bit of work!

In order to implement autocomplete behavior, we have to set it up so that the value of the search_input field is set from `form_component.ex`, probably by an event handler. That's a challenge: how do we set the value of form fields from event handlers? Normally the value is typed in. The best I can think of is to set the value of the field equal to an assign and change that assign in the event handler.

This was fun to build and the only other example I can find uses AlpineJS. I did it without any JS so some LiveView developers would probably be interested to see how to do this.

Hmm... Not saving to the db yet! We also have the problem that if the query is a substring of another string that comes before it alphabetically, that other string will be saved.

Okay, corrected both of those by having it check to see if an exact match exists in the list before defaulting to the first result.

Next steps:
1. Make tests pass.
   1. Add fixture for countries
   2. Call country fixture to create a country in the providers test
   3. Pass that country as an argument to the vps fixture called in the providers test.
2. Merge `form_component.ex` to edit parent.
3. Contact kyle for further feedback
4. Apply feedback
5. Fix up subsequent PRs with merge/rebase.
** Friday 3/03
*** NA-I119-vps-management
Make the tests pass (step 1. from yesterday).
** Monday 3/06
